name = "Sisyphus"
author = "Explosivejoe190"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff95992102f40daa133583dbba284e463adc58fab46b89ebde3319c5a85ee538"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
