name = "Sisyphus"
author = "Explosivejoe190"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b4be5b17e28ffeadc6cf42e9c7c67ce9af2ea56b5b7ad58116ac8893999e973"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
