
["General Common"]
	#Enable Hot Coal turning in to Burning Coal? (True)
	BurningCoal = true
	#Enable the Ventilation system? (True)
	VentSystem = true
	#The cubic number of blocks effected by Burning Coal (16.0)
	BurningCoalRange = 16.0
	#The cubic number of blocks effected by the Ventilation System (16.0)
	VentSystemRange = 16.0
	#Enable Sanity? (True)
	Sanity = true
	#Gas Mask drain multiplier (0.01 | divided by 10 & 20 for the other masks)
	GasMaskDrain = 0.01
	#Cave toxicity starting Y level (63.0)
	ToxicityStart = 63.0
	#Enable Lung Damage? (True)
	LungDamage = true
	#Keep Lung Damage on death? (False)
	KeepLungDamage = false
	#Limit the mod to only work in the Overworld? (False)
	LimitOverworld = false
	#If enabled shows Gas Leaks through the walls using the glowing effect but they will still play ambient chime noises so that players can locate them
	GasLeakVisual = true

